export default {
  DraftbitTeamPhoto: require('../assets/images/DraftbitTeamPhoto.jpg'),
  DraftbitIcon: require('../assets/images/DraftbitIcon.png'),
  Guac: require('../assets/images/Guac.jpg'),
  Sky: require('../assets/images/Sky.jpg'),
  PermissionsNotification: require('../assets/images/PermissionsNotification.png'),
  ProfilePlaceholder: require('../assets/images/ProfilePlaceholder.png'),
  Logo2: require('../assets/images/Logo2.png'),
  DraftbitMark: require('../assets/images/draftbit-mark.png'),
  Companylogo: require('../assets/images/Companylogo.png'),
  _062812: require('../assets/images/062812.png'),
  _888: require('../assets/images/888.jpg'),
  Slider31: require('../assets/images/Slider31.jpg'),
  Slider11: require('../assets/images/Slider11.jpg'),
  Slider11: require('../assets/images/Slider11.jpg'),
};
